# -*- coding: utf-8 -*-
"""CS 398 Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kgOb_u0XTnKWPO8LATugRAgf20capIQj
"""

import numpy as np
import matplotlib.pyplot as plt

data = open('ProfileData.txt', 'r')
Lines = data.readlines()

separatedLines = []

xVals = []
yVals = []

for line in Lines:
  tempDate, tempType, tempDesc, tempVal = line.split(',')
  tempVal = tempVal.replace('\n', '')
  tempRow = [tempDate, tempType, tempDesc, int(tempVal)]
  separatedLines.append(tempRow)

sortedSeparatedLines = sorted(separatedLines, key=lambda x: x[2])

i = 0
while i < len(sortedSeparatedLines):
  tempLine = sortedSeparatedLines[i]
  xVals.append(tempLine[2])
  sum = tempLine[3]
  count = 1
  i = i + 1
  while i < len(sortedSeparatedLines) and tempLine[2] == sortedSeparatedLines[i][2]:
    count = count + 1
    sum = sum + sortedSeparatedLines[i][3]
    i = i + 1
  yVals.append(sum / count)
  i = i + 1

plt.bar(xVals, yVals,
        width = 0.4)
 
plt.xlabel("Description")
plt.xticks(rotation = 90)
plt.ylabel("Average Time (ms)")
plt.show()